# Site settings
title: Jmexe's Blog
email: mjia.zb@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jmexe.github.io" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
# twitter:  username
# weibo:    ID
github:   jmexe
# codepen:  username
# dribbble: username


# Comment
disqus_shortname: jmexeblog


# Google Analytics
google_analytics: 112588791


# Build settings
markdown: kramdown

highlighter: pygments #pygments
lsi: false
safe: false

sass:
  style: compressed
gems:
  - jekyll-sitemap
